### ISSUE TITLE
Enhancement, Complete TR5 SoundPack ready to use for OpenTomb.

### ISSUE THREAD

**Issue by Nightshades1** [TeslaRus/OpenTomb#6]
![Imgur](http://i.imgur.com/1I0bRzn.jpg)

So yeah i wanted to contribute, i don't know what's going on with these troll on tombraiderforum, i have made my first account and i got an instant ban lol, then made new account and instant ban too, look's like they don't like Nightshades name so sorry to contact you from github but no choice.

So I spent more than 1 day on this, Extracted all sounds of the game, completely reconverted all sounds in HQ .ogg bitrate, and the best thing (off course) Organized all Sound(s) (made a quick macro to rename everything) to their "Official Name". with the help of the PSX SDK =P.

You can get it from my account here ...

Oh and that wallpaper was made for you lol, Cya and good luck coding the engine ! ♥

**Comment by TeslaRus** [comment]
thx, but I contribute **only** source and minimal engine binaries / configs / scripts, no one original game resources.
